### ISSUE TITLE
Buttons being wide in the Demographics survey

### ISSUE THREAD

**Issue by niccolopaganini** [e-mission/e-mission-docs#1015]
Under the OpenPATH Demographics survey -> Under job related information -> The question "Do you work full-time or part-time at the primary job" has buttons which are wider than other buttons in the survey page. This was observed in both Android and iOS devices.

 **Photographs for reference:**

<table>
  <tr>
    <td><img src="https://github.com/e-mission/e-mission-docs/assets/69108657/c316b8c7-3c0c-4ea7-941b-01113bbbf307" alt="Image 1 missing"></td>
    <td><img src="https://github.com/e-mission/e-mission-docs/assets/69108657/7bd36881-072b-4aed-83c3-bc441cd435ca" alt="Image 2 missing"></td>
  </tr>
  <tr>
    <td><img src="https://github.com/e-mission/e-mission-docs/assets/69108657/7d79111d-dc58-4e11-8422-ca3bfca7a271" alt="Image 3 missing"></td>
    <td><img src="https://github.com/e-mission/e-mission-docs/assets/69108657/565e893d-ae29-43c9-8862-f2c9c2cd1758" alt="Image 4 missing"></td>
  </tr>
</table>

**Comment by niccolopaganini** [comment]
Tagging @JGreenlee for visibility

**Comment by niccolopaganini** [comment]
I updated the app version to 1.5.5 and checked this specific page again and it seems to be the same case. @Abby-Wheelis suggested verify in both versions of OPcodes (study and program) and it seems to be the case for both; and for both Android and iOS.

**Comment by JGreenlee** [comment]
I am fairly certain this is due to the first few lines of `styles.css`

```css
.enketo-plugin {
  @import 'enketo-core/src/sass/formhub/formhub.scss';
  flex: 1;
  .question.non-select {
    display: inline-block;
  }
  .question input[name*="_date"],
  .question input[name*="_time"] {
    width: calc(40vw - 10px);
    margin-right: 5px;
    display: flex;
  }
}
```

Most likely a regression from when we upgraded Enketo versions several months ago

**Comment by JGreenlee** [comment]
Actually this is due to an unlikely coincidence!

We have these styles so that on timeuse surveys, the date and time inputs show next to each other rather than each taking up their own line.

So rather than
```
|--- Start Date ---|
|--- Start Time ---|
|--- End Date -----|
|--- End Time -----|
```
we show
```
|-- Start Date -- | -- Start Time --|
|--- End Date --- | --- End Time ---|
```
for a bit nicer experience.

By our specification, timeuse surveys contain fields called `"Start_time"`, `"End_time"`, `"Start_date"`, and `"End_date"` if they are going to have time-based inputs.
So my intent with this CSS was that with any input ending in `_time` or `_date`, we would fit 2 evenly on one line.

But for this particular question on the demographics survey, the `<input>` is:
```html
<input type="radio" name="/data/group_yk8eb99/Do_you_work_full_time_or_part_" data-name="/data/group_yk8eb99/Do_you_work_full_time_or_part_" value="full_time" data-required="true()" data-type-xml="string">
```
It's a coincidence that the name is `/data/group_yk8eb99/Do_you_work_full_time_or_part_` which is a string containing `_time`.

And apparently in CSS, `*=` matches 'containing' strings not 'ending' strings https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors#substring_matching_selectors
I guess I was looking for `$=`.

In any case, after seeing this I think it would be safer to just explicitly check each of `"Start_time"`, `"End_time"`, `"Start_date"`, and `"End_date"`.

**Comment by JGreenlee** [comment]
I think the fix would be

```css
.enketo-plugin {
  @import 'enketo-core/src/sass/formhub/formhub.scss';
  flex: 1;
  .question.non-select {
    display: inline-block;
  }
  .question input[name$="Start_date"],
  .question input[name$="Start_time"],
  .question input[name$="End_date"],
  .question input[name$="End_time"] {
    width: calc(40vw - 10px);
    margin-right: 5px;
    display: flex;
  }
}
```

@niccolopaganini Since you found this issue, would you be able to (at your convenience) implement the following fix, verify that it resolves the issue, and put together a PR for it?
This is not currently urgent / not a showstopper
