### ISSUE TITLE
Docker phone devapp load from a fork

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#655]
If I would like to load from my own fork would I need to upload my image to Docker Hub as well? then change `image:` to my docker repo?

```
version: "3"
services:
  devapp-server:
    image: emission/e-mission-phone.dev.ui-only:latest
    environment:
      - PHONE_REPO=https://github.com/asiripanich/e-mission-phone.git
      - PHONE_BRANCH=rciti1
```
https://github.com/e-mission/e-mission-docker/blob/c35bbd45efa8fd853e8180916acca237bcffc697/examples/em-phone-devapp-serve/docker-compose.livereload.yml#L3-L7
